package Prova;

public enum Token {
	NOME_VARIAVEL,
	INT,
	DEC,
	ESTRUTURA_REPETICAO,
	PALAVRA_CHAVE,
	INICIO_FUNCAO,
	FINAL_FUNCAO,
	ESTRUTURA_DECISAO,
	TIPO_VARIAVEL,
	OPERADOR_LEITURA,
	OPERADOR_IMPRIMIR,
	FUNCAO_LEITURA,
	FUNCAO_IMPRIMIR,
	OPERADOR_COMPARACAO,
	RETORNO_FUNCAO,
	OPERADOR_INCREMENTO,
	BRANCO;
}
